### ISSUE TITLE
Bacalhau Computations Workflow

### ISSUE THREAD

**Issue by tse-lao** [tse-lao/hackathon-fvm#28]
@tse-lao 
- [x] test and integrate the createJob( )
- [x] Call the looking for a job function in the backend and start the execution. 
- [x] Automatically update jobID with bacalhau Job id  <-- waiting for the function Sc
- [x] Automatically update the result oft he computation in tableland with function ExecuteFulfilled()

@nijoe1 
- [x] add function for changing status to pending => to started and insert jobID in tableland query. 
- [x] Change from job started rewarding to execute fulfill rewarding.

**Comment by tse-lao** [comment]
@nijoe1  I will add the jobID once the function is there, when the results are done we can request the result of the job. 
if the result is completed we can update the status, otherwise we just leave it open. This reduced the workload to subscribe to job_id and track if its updated. For now this seems to be a valid way of doing it. 
In the future we might need to consider another consideration.

**Comment by nijoe1** [comment]
To scale the process we can assign more than one executor ( Bacalhau servers ). When a server receives an execution Request it will check if this request is taken from another one. When a server is running a job it could also listen to events and add them to a queue.  Another thing to consider is to use libp2p to create a network for our servers to communicate and execute things efficiently.
